"""initial schema

Revision ID: 19068e2673bf
Revises: 
Create Date: 2026-05-11 22:06:45.235553

"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19068e2673bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoints_expires_at'), 'endpoints', ['expires_at'], unique=False)
    op.create_index(op.f('ix_endpoints_token'), 'endpoints', ['token'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query_string', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_preview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('body_size', sa.Integer(), nullable=False),
    sa.Column('blob_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_endpoint_id'), 'requests', ['endpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_endpoint_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_endpoints_token'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_expires_at'), table_name='endpoints')
    op.drop_table('endpoints')
    # ### end Alembic commands ###
